language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly" # currently points to 3.7-dev
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: pytest
#env:
#- DJANGO_VERSION=1.7.8
#- DJANGO_VERSION=1.8.2
#install:
# - pip install -q Django==$DJANGO_VERSION
#- python setup.py -q install