# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 10:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funeral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date of the Funeral')),
                ('type', models.TextField(verbose_name='Type of Burial')),
                ('location', models.TextField(verbose_name='Location')),
                ('tombstone', models.BooleanField(verbose_name='Tombstone wanted?')),
                ('layed_out', models.BooleanField(verbose_name='User wants to be layed out?')),
                ('additional_comments', models.TextField(verbose_name='Additional Comments')),
                ('deceased', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheer', models.TextField(verbose_name='Words of Cheer')),
                ('guest_list', models.TextField(verbose_name='Guest List')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
